name: Deploy to Digital Ocean
on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: rocly-latest
    steps:
      - name: Deploy Gridsome site
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} #user on server

        script:
          mkdir test #create folder to deploy to in live server
          cd test #endter into deploy folder
          git clone git@github.com:Alex-L-Crane/alexcrane-website.git #clone the repo
          echo 'Alex Crane website successfully deployed to Digital Ocean' #confirmation message
